console.log("==============================")
console.log("           COXINHAZ           ")
console.log("------------------------------")
console.log("      Detalhes do pedido      ")
console.log("------------------------------")
console.log("Item          Quant.   Preco  ")
console.log("------------------------------")
console.log("🥖 Churrinhos    20     15.9 ")
console.log("🥚 Coxinhas      50     21.9 ")
console.log("🥤 Coca Zero     01      5.0 ")
console.log("💧 Água 510mL    01      3.0 ")
console.log("------------------------------")
console.log("Desconto               - 10.0 ")
console.log("Total                    35.8 ")
console.log("==============================")
